"""empty message

Revision ID: 231830020bc1
Revises: 65442885e87d
Create Date: 2022-12-16 23:09:25.700219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231830020bc1'
down_revision = '65442885e87d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'name')
    # ### end Alembic commands ###
