"""empty message

Revision ID: 44da04dfe6cb
Revises: 690651a2f6d8
Create Date: 2022-12-17 10:12:44.182036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44da04dfe6cb'
down_revision = '690651a2f6d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instrument_instrument_type_id_fkey', 'instrument', type_='foreignkey')
    op.drop_column('instrument', 'instrument_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('instrument_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('instrument_instrument_type_id_fkey', 'instrument', 'instrument_type', ['instrument_type_id'], ['id'])
    # ### end Alembic commands ###
