"""empty message

Revision ID: 65442885e87d
Revises: 868183897650
Create Date: 2022-12-16 23:01:32.549961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65442885e87d'
down_revision = '868183897650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('instrument_degree', sa.Float(), nullable=True))
    op.drop_column('instrument', 'instrument_type_degree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('instrument_type_degree', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('instrument', 'instrument_degree')
    # ### end Alembic commands ###
