"""empty message

Revision ID: 690651a2f6d8
Revises: 828fa50b57fe
Create Date: 2022-12-17 10:04:47.144954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690651a2f6d8'
down_revision = '828fa50b57fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument', 'data')
    # ### end Alembic commands ###
