"""empty message

Revision ID: 828fa50b57fe
Revises: e3fcd030e724
Create Date: 2022-12-17 02:04:44.463535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828fa50b57fe'
down_revision = 'e3fcd030e724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('portfolio_questions_answer_id_fkey', 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'questions_answer_id')
    op.add_column('questions_answer', sa.Column('portfolio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions_answer', 'portfolio', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions_answer', type_='foreignkey')
    op.drop_column('questions_answer', 'portfolio_id')
    op.add_column('portfolio', sa.Column('questions_answer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('portfolio_questions_answer_id_fkey', 'portfolio', 'questions_answer', ['questions_answer_id'], ['id'])
    # ### end Alembic commands ###
