"""empty message

Revision ID: 868183897650
Revises: 8e8a11f09b74
Create Date: 2022-12-16 22:51:02.403952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868183897650'
down_revision = '8e8a11f09b74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('instrument', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument', 'price')
    op.drop_column('instrument', 'amount')
    # ### end Alembic commands ###
