"""empty message

Revision ID: 8e8a11f09b74
Revises: b7b9f27c6070
Create Date: 2022-12-16 22:22:41.751803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8a11f09b74'
down_revision = 'b7b9f27c6070'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
